# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f0d6b321c4656f11dfeb7953d26abff6"
name = "Product Waivers"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[[webhooks.subscriptions]]
topics = ["orders/create"]
uri = "/webhooks/orders/create"

[app_proxy]
url = "https://example.com"
subpath = "product-waivers"
prefix = "apps"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_themes,write_files,read_orders,write_orders"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
